config/routes.rb
PartyBusCheckin::Application.routes.draw do

  match 'guestgroup' => 'guests#guestgroup', :as => :guestgroup
  match 'deleteguests' => 'guests#deleteguests', :as => :deleteguests
  match 'uncheckall' => 'guests#uncheckall', :as => :uncheckall
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => 'signout'
  
  resources :guests do
    get :checkedin, on: :member
    get :uncheckedin, on: :member
  end
  
  root :to => "guests#index"

  match '*a', :to => 'sessions#routingerror'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  attr_accessible :name, :locator, :tickets_bought, :event_date, :guest_group
  
  def self.search(search)
    if search
      @guests = Guest.order(:name).find(:all, :conditions => [ 'name ILIKE ?', "%#{search}%"]) #ILIKE is the Postgres way for case insensitive
    else
      @guests = Guest.order(:name).find(:all)
    end
  end
  
  def self.checkedin(value)
    @guests = Guest.find(:all, :conditions => ['checked_in = ?', value])
  end
  
  #Logic to parse guest group
  def self.createGuestGroup(group, event_date, guestgroup)
    
    arr = group.split(/\n/)

    arr.each do |i|
      tokens = i.split("(")
      tix_locator = tokens[1] #e.g. "1 tix - SSSAAA"
      # p tokens
      #Name
      name = tokens[0]
      tix_locator_split = tix_locator.split
      #Number of Tickets
      num_tickets = tix_locator_split[0]
      #Locator
      locator = tix_locator_split[3].chomp(")") #To remove last ')'

        # p "==Creating Guest=="
        #         p name
        #         p num_tickets
        #         p locator
      
      Guest.create!(:name => name, :tickets_bought => num_tickets, :locator => locator, :event_date => event_date, :guest_group => guestgroup)
    end
  end
  
  def self.checkIn(guest, value)
    if value
      guest.checked_in = true 
    else
      guest.checked_in = false
    end 
    guest.save
    
    # respond_to do |format|
    #       format.html { redirect_to guests_url }
    #       format.js
    #     end
  end
  
  
  def self.uncheckall
    @guests = Guest.update_all("checked_in = false")
  end
  
end

app/models/guestgroup.rb
class Guestgroup < ActiveRecord::Base
  attr_accessible :type, :date

  validates :type, :presence => true
  validates :date, :presence => true
end

app/models/host.rb
class Host < ActiveRecord::Base
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/user.rb
class User < ActiveRecord::Base
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.email = auth['info']['email']
      user.name = auth['info']['name']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  private
  
    def current_user
      #@current_user ||= User.find(session[:user_id]) if session[:user_id]
      @current_user ||= session[:user] if session[:user]
    end
  
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_filter :find_guest, :only => [:show, :edit, :update, :destroy, :checkedin, :uncheckedin]
  
  def index
     # @client_ip = request.remote_ip
     #       @remote_ip = request.env["HTTP_X_FORWARDED_FOR"]
     #       @my_ip = request.env["HTTP_X_FORWARDED_FOR"] || request.remote_addr
     #       @ip_addr = request.env['REMOTE_ADDR']
    
    
    @guest = Guest.first
    if params[:checkedin]
      @guests = Guest.checkedin(params[:checkedin].to_bool)
    else
      @guests = Guest.search(params[:search])
    end
    
  end

  def show
    
  end

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(params[:guest])
    if @guest.save
      redirect_to @guest, :notice => "Successfully created guest."
    else
      render :action => 'new'
    end
  end

  def edit
    
  end

  def update
    if @guest.update_attributes(params[:guest])
      redirect_to guests_url, :notice  => "Successfully updated guest."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @guest.destroy
    redirect_to guests_url, :notice => "Successfully destroyed guest."
  end
  
  def checkedin
    Guest.checkIn(@guest, true)
    redirect_to guests_url, :notice => "Guest was succussfully checked in!"
  end
  
  def uncheckedin
    Guest.checkIn(@guest, false)
    redirect_to guests_url, :notice => "Guest was succussfully Unchecked in!"
  end
  
  def guestgroup
    @hosts = Host.order(:name).find(:all)
    if params[:guestgroup]
      guestgroup = Guestgroup.new(:type =>params[:type], :date => params[:event_date])
      if guestgroup.save
        Guest.createGuestGroup(params[:guestgroup], params[:event_date], guestgroup.id)
      end
      
      redirect_to guests_url  
    end
  end
  
  def deleteguests
    @Guests = Guest.delete_all
    redirect_to guests_url
  end
  
  def uncheckall
    Guest.uncheckall
    redirect_to guests_url
  end
  
  private 
    def find_guest
      @guest = Guest.find(params[:id])
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    auth = env['omniauth.auth']
    user = User.find_by_email(auth['info']['email']) || User.create_with_omniauth(auth)
    session[:user] = user
    redirect_to root_url
  end
  
  def destroy
    session[:user] = nil
    redirect_to root_url
  end
  
  def routingerror
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/guests/_form.html.erb
<%= form_for @guest do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :locator %><br />
    <%= f.text_field :locator %>
  </p>
	<p>
    <%= f.label :event_date %><br />
    <%= f.text_field :event_date %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/guests/edit.html.erb
<% title "Edit Guest" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @guest %> |
  <%= link_to "View All", guests_path %>
</p>

app/views/guests/guestgroup.html.erb
<h2>Guest Group</h2>
<h3> Instructions: Copy and paste</h3>

<p>
	Sample: <br/>
	<pre>
  Jonathan Edge (1 tix - ZCLCMT)
  Sara Pappa (1 tix - BIHJPB)
  Mason Barret (1 tix - AMXZZY)
	</pre>
</p>

<%= form_tag guestgroup_path do %>
	<p>
		<%= label_tag 'guestgroup', 'Guest Group' %>
		<%= text_area_tag "guestgroup", nil, :rows => 30, :cols => 50 %>
	</p>
	<p>
		<%= label_tag "event_date", "Event Date" %>
		<%= text_field_tag "event_date", "10/21/2011" %>
	</p>
	<p>
		<%= label_tag "event_type", "Event Type" %>
		<%= select_tag "type", "<option>NightBus</option><option>Vineyard</option>".html_safe %>
	</p>
	<p>
		<%= label_tag "host", "Host" %>
		<%= select_tag "host", options_from_collection_for_select(@hosts, "name", "name") %>
	</p>
	<%= submit_tag "Add Guests", :name => nil %>
<% end %>

<%= link_to "Go Back", guests_url %>

app/views/guests/index.html.erb
<% title "Guests" %>


<%= form_tag guests_path, :method => 'get' do %>
	<p>
	  <%= text_field_tag :search, params[:search] %>
	  <%= submit_tag "Search", :name => nil%>
	</p>
<% end %>

<%# If there is at least 1 guest%>
<% if @guest %>
  <p>
    <b>Guests for:</b> <i><%= @guest.event_date %></i>
	<br/>
	<b>Total Guests:</b> <%= @guests.count %>
	<br/>
	
	<table>
	  <tr>
	    <th>Guest</th>
		<th># Tickets</th>
	    <%# <th>Record Locator</th> %>
		<%# <th>Date</th>%>
		<th></th> <!-- Checkin-->
		<th></th> <!-- UnCheckin-->
	  </tr>
	  <% for guest in @guests %>
	    <tr id="guest_<%= guest.id %>">

		  <% if guest.checked_in? then %>
	      	<td class="checked_in"><%= guest.name %></td>
		  <% else %>
			<td><%= guest.name %></td>
		  <% end %>

		  <td><%= guest.tickets_bought %></td>      
		  <%# <td><%= guest.locator ></td>%>
		  <%#<td><%= guest.event_date ></td> %>
			<% if guest.checked_in? then %>
				<td class="checked_in">Yes!</td>
				<td><%= link_to "Uncheck In", uncheckedin_guest_path(:id => guest.id) %></td>
			<% else %>
				<td><%= link_to "Check In", checkedin_guest_path(:id => guest.id) %></td>
				<td></td>
			<% end %>

	      <%#<td><%= link_to "Details", guest ></td>%>
		  <%# <td><%= link_to "Edit", edit_guest_path(guest) ></td>%>
		  <%#<td><%= link_to "Delete", guest, :confirm => "Are you sure?", :method => :delete ></td> %>
	    </tr>
	  <% end %>
	</table>

  </p>
<% else %>
  <p>No Guests on list</p>
<% end %>


<%#<p><%= link_to "New Guest", new_guest_path ></p>%>
<%#<p><%= link_to "New Guest List", guestgroup_path ></p>%>
<%#<p><%= link_to "View All Checked In", guests_path(:checkedin => true) ></p>%>
<%#<p><%= link_to "View All UnChecked In", guests_path(:checkedin => false) ></p>%>
<%#<p><%= link_to "View All", guests_path ></p>%>
<%#<p><%= link_to "Uncheck All", uncheckall_path ></p>%>
<%#<p><%= link_to "Delete All", deleteguests_path, :confirm => "ALL GUESTS WILL BE DELETED, ARE YOU SURE?" ></p>%>

<p><%= button_to "View All", guests_path, method: :get %></p>
<p><%= button_to "View All Checked In", guests_path(:checkedin => true), method: :get %></p>
<p><%= button_to "View All UnChecked In", guests_path(:checkedin => false), method: :get %></p>

<p><%= button_to "New Guest List", guestgroup_path %></p>
<p><%= button_to "Uncheck All", uncheckall_path, :confirm => "All guests will be marked as NOT CHECKED IN, are you sure?" %></p>
<p><%= button_to "Delete All", deleteguests_path, :confirm => "ALL GUESTS WILL BE DELETED, ARE YOU SURE?" %></p>

app/views/guests/new.html.erb
<% title "New Guest" %>

<%= render 'form' %>

<p><%= link_to "Back to List", guests_path %></p>

app/views/guests/show.html.erb
<% title "Guest" %>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>
<p>
  <strong>Tickets Bought:</strong>
  <%= @guest.tickets_bought %>
</p>
<p>
  <strong>Locator:</strong>
  <%= @guest.locator %>
</p>
<p>
  <strong>Event Date:</strong>
  <%= @guest.event_date %>
</p>
<p>
  <strong>Checked In?</strong>
  <%= @guest.checked_in %>
</p>


<p>
  <%= link_to "View All", guests_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PartyBusCheckin</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>

  <meta name="viewport" content="width=device-width, initial-scale=1"> 

  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.min.css" />
  <script src="http://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.min.js"></script>
  <%= csrf_meta_tags %>
</head>	
<body>

<div data-role="page">
	<center>
	  <h2>PartyBus Checkin!</h2>	
	
	  <% if current_user %>
		Welcome <%= current_user.name %>
		<!-- ONly add access to add users for me (for now)-->
		<% if current_user.name == "Americo" %>
			<%= link_to "Add User", '/auth/identity/register/'%>
		<% end %>
	    <%= link_to "Sign out", signout_path %>
	
		<%= yield %>
	
	  <% else %>
		<%#= link_to "Add User", '/auth/identity/register/'%>
		
		<h3>Please Sign in:</h3>
		<%= form_tag "/auth/identity/callback" do %>
			<div class="field">
				<%= label_tag :auth_key, "Email" %> <br>
				<%= text_field_tag :auth_key %>
			</div>
			<div class="field">
				<%= label_tag :password %> <br>
				<%= password_field_tag :password %>
			</div>
			<div><%= submit_tag "Login" %></div>
		<% end %>
	  <% end %>
	
	</center>
</div>
</body>
</html>

app/views/layouts/guest.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "guest" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>